
BASETIMEFRAME = 1
GREEN = "GREEN"
RED = "RED"
tag = "tag"

STRATEGYID = "STRATEGYID"
INSTRUMENT = "INSTRUMENT"
TIMEFRAME = "TIMEFRAME"
PARAMETERID = "PARAMETERID"
CLOSING_BASIS = "CLOSING_BASIS"
CONTINUOUS_BASIS_STEP  = "CONTINUOUS_BASIS_STEP"
FUNCTIONS = "FUNCTIONS"
FUNCTION9_COMBINATION = "FUNCTION9_COMBINATION"
FUNCTION9 = "FUNCTION9"

#FUNCTIONS
FUNCTIONS_F8 = "F8"
FUNCTIONS_F9 = "F9"
FUNCTIONS_F10 = "F10"
FUNCTIONS_F11 = "F11"
FUNCTIONS_F13 = "F13"
FUNCTIONS_F13_1 = "F13_1"
FUNCTIONS_F13_3 = "F13_3"
FUNCTIONS_F14 = "F14"
FUNCTIONS_F15 = "F15"


## COMMON
VALUE1 = "VALUE1"
VALUE2 = "VALUE2"
VALUE3 = "VALUE3"
VALUE4 = "VALUE4"

OHLC_DT = "dt"
OHLC_OPEN = "o"
OHLC_HIGH = "h"
OHLC_LOW = "l"
OHLC_CLOSE = "c"
OHLC_VOLUME = "v"
OHLC_END_DT = "e_dt"



K = "%K"
EMA = "EMA"
SMA = "SMA"
D = "%D"

#Stochastic 
STOCHASTIC_VALUE_K = "k"
STOCHASTIC_VALUE_D = "d"
STOCHASTIC_K_EMA = "k_ema"
STOCHASTIC_K_EMA = "k_ema"


#PCR
PCR_SMA = "PCR_SMA"
ZSCORE_SMA = "ZSCORE_SMA"



## FRACTAL

PRE_FRACTAL_LONG = "PRE_FRACTAL_LONG"
PRE_FRACTAL_SHORT = "PRE_FRACTAL_SHORT"
FRACTAL_LONG  = "FRACTAL_LONG"
FRACTAL_SHORT  = "FRACTAL_SHORT"
FRACTAL_CONFIRMED_LONG = "FRACTAL_CONFIRMED_LONG"
FRACTAL_CONFIRMED_SHORT = "FRACTAL_CONFIRMED_SHORT"
FRACTAL_TAG_DT = "FRACTAL_TAG_DT"

## BB

MEAN_BAND = "MEAN_BAND"
UPPER_BAND = "UPPER_BAND"
LOWER_BAND = "LOWER_BAND"

## F13

F13_PERIOD = "F13_PERIOD"

##F14

SMA_1 = "SMA1"
SMA_2 = "SMA2"
PER = "PER"


datetime_collection = []
tf_start_end_time = {}